name: Build CLI utilities
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64, x86]
        platform: [win, linux]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build CLI utilities
      shell: pwsh
      run: |
        msbuild /m /t:restore,cli\uupmediaconverter:publish,cli\uupdownload:publish /p:Platform=${{ matrix.architecture }} /p:RuntimeIdentifier=${{ matrix.platform }}-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}/CLIs /p:PublishSingleFile=true /p:PublishTrimmed=false /p:Configuration=Release UUPMediaCreator.sln
      continue-on-error: true

    - name: Create PDB Output Directory
        shell: pwsh
        run: |
          mkdir ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\PDBs
        continue-on-error: true

      - name: Move PDBs
        shell: pwsh
        run: |
          move ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\CLIs\*.pdb ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\PDBs\
        continue-on-error: true

      - name: Upload artifact (Binaries)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}-binaries
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}\CLIs
        continue-on-error: true

      - name: Upload artifact (Symbols)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}-symbols
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}\PDBs
        continue-on-error: true
